[tool.poetry]
name = "flask-tailwind-project"
version = "0.1.0"
description = ""
authors = ["Stewart Alsop"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
flask = "^3.0.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
